---
development:
  cloud_name: dxxi1mmco
  api_key: <%= ENV['CLOUDINARY_APIKEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: dxxi1mmco
  api_key: <%= ENV['CLOUDINARY_APIKEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dxxi1mmco
  api_key: <%= ENV['CLOUDINARY_APIKEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
